apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroshield-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/Wildfire-Containment-Resource-Deployment.git'
    path: helm/pyroshield
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pyroshield
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
