apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: pyroshield
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pyroshield
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pyroshield
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "{{ .Values.monitoring.prometheus.enabled }}"
        prometheus.io/port: "{{ .Values.config.apiPort }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: pyroshield-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.apiPort | int }}
          env:
            - name: MODEL_PATH
              value: "{{ .Values.config.modelPath }}"
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.config.mlflowUri }}"
            - name: API_HOST
              value: "{{ .Values.config.apiHost }}"
            - name: API_PORT
              value: "{{ .Values.config.apiPort }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.apiPort | int }}
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.apiPort | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
